<div class="col-span-5 pt-16 px-24 h-full bg-gradient-to-b from-slate-200 to-neutral-200">
  @switch($show)
    @case('dashboard')
      @include('/modules/cardholder/dashboard')
      @break
    @case('claims')
      @include('/modules/cardholder/claims')
      @break
    @case('projects')
      @include('/modules/cardholder/projects')
      @break
    @case('polls')
      @include('/modules/cardholder/polls')
      @break
    @case('calendar')
      @include('/modules/cardholder/calendar')
      @break
    @default
      @include('/modules/cardholder/dashboard')
  @endswitch
</div>